replicas: 1

image:
  repository: ghcr.io/jont828
  name: cluster-api-visualizer
  imagePullPolicy: Always

label: 
  key: app
  value: capi-visualizer

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  #annotations:
  #  cert-manager.io/cluster-issuer: vault
  hostname: capi-visualizer.local
  tls: [] 
  #  - hosts:
  #      - capi-visualizer.local
  #    secretName: capi-visualizer-cert